### ISSUE TITLE
Database Configurations 

### ISSUE THREAD

**Issue by salexstephen** [cloudfoundry-community/tomee-buildpack#24]
We are migrating apps from websphere environment to PCF. Currently, the dependent jar in the app uses JNDI lookup to make the database connection. So we choose tomee buildpack to deploy the app in PCF.
Tomee buildpack creates jndi entries in the resources.xml and will read connection details through CUPS created for that app.

Now we trying to set the connection pool details like (maxActive, maxIdle) properties as like websphere. We tried couple of ways to set those configuration, but couldn’t able to read the configuration details through our java code.

1)	configured –Djdbc/jndiname.maxActive=50  through JAVA_OPTS in the manifest.yml. 
2)	Tried by adding the maxActive as a parameter while creating the CUPS.

But in both the cases, we getting the max connection as zero in the JAVA code.

•	Please share me the steps to configure the connection pool properties?
•	Please share me the steps to test the connection pool properties?

**Comment by violetagg** [comment]
Hi,

Provide with your application binaries `WEB-INF/resources.xml` configured with these properties.
For example:

```
<resources>
  <Resource id="jdbc/jndiname">
    maxActive=50
    ...
  </Resource>
</resources>
```

In the `Resource` element it is needed just to configure `jndiname` which is the name of the service and the connection pool properties. All the rest as u/p, url etc. will be taken from the service.

Regards,
Violeta

**Comment by salexstephen** [comment]
thanks for the update,
is there any way to test the connection pool properties through java code?

**Comment by violetagg** [comment]
Try using JMX. Search for MBean in the `domain` `openejb.management` with `className` `org.apache.tomcat.jdbc.pool.jmx.ConnectionPool`

**Comment by salexstephen** [comment]
Hi ,
I tried your solution by adding the resources.xml in the WEB-INF folder. 
the application couldn't able to find the datasource connection details and got null pointer exception.

 2017-10-03T17:44:19.48+0530 [APP/PROC/WEB/0] OUT java.lang.NullPointerException
   2017-10-03T17:44:19.48+0530 [APP/PROC/WEB/0] OUT     at org.apache.openejb.config.AutoConfig.processApplicationResources(AutoConfig.java:947)
   2017-10-03T17:44:19.48+0530 [APP/PROC/WEB/0] OUT     at org.apache.openejb.config.AutoConfig.deploy(AutoConfig.java:190)
   2017-10-03T17:44:19.48+0530 [APP/PROC/WEB/0] OUT     at org.apache.openejb.config.ConfigurationFactory$Chain.deploy(ConfigurationFactory.java:420)
   2017-10-03T17:44:19.48+0530 [APP/PROC/WEB/0] OUT     at org.apache.openejb.config.ConfigurationFactory.configureApplication(ConfigurationFactory.java:1037)
   2017-10-03T17:44:19.48+0530 [APP/PROC/WEB/0] OUT     at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1276)
   2017-10-03T17:44:19.48+0530 [APP/PROC/WEB/0] OUT     at org.apache.tomee.catalina.TomcatWebAppBuilder.configureStart(TomcatWebAppBuilder.java:1124)
   2017-10-03T17:44:19.48+0530 [APP/PROC/WEB/0] OUT     at org.apache.tomee.catalina.GlobalListenerSupport.lifecycleEvent(GlobalListenerSupport.java:133)
   2017-10-03T17:44:19.48+0530 [APP/PROC/WEB/0] OUT     at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
   2017-10-03T17:44:19.48+0530 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5087)
   2017-10-03T17:44:19.48+0530 [APP/PROC/WEB/0] OUT     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
   2017-10-03T17:44:19.48+0530 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)

I logged into the application VM through ssh and found resources.xml having couple of entries for the same JNDI Name. it seems Tomee creating a new entry in the resources.xml instead of updating the existing one.

vcap@bc50491d-fd43-4400-6657-a0a2:~/app/WEB-INF$ cat resources.xml
<?xml version='1.0' encoding='UTF-8'?>
<resources>
    <Resource name='jdbc/framework' type='DataSource' auth='Container' driverClassName='com.ibm.db2.jcc.DB2Driver' factory='org.apache.tomcat.jdbc.pool.DataSourceFactory' removeAbandonedTimeout='60' testWhileIdle='true' timeBetweenEvictionRunsMillis='300000' connectionProperties='useUnicode=true;useJDBCCompliantTimezoneShift=true;useLegacyDatetimeCode=false;serverTimezone=UTC;' initialSize='8' maxActive='8' minIdle='8' maxIdle='8'/>
    <Resource id='jdbc/framework' type='DataSource' properties-provider='org.cloudfoundry.reconfiguration.tomee.DelegatingPropertiesProvider'/>
</resources>

**Comment by violetagg** [comment]
Did you specify the `Resource`'s `id` as I proposed `id="jdbc/<service-name>"`?

**Comment by salexstephen** [comment]
sorry it's my mistake, I placed service name inside the name attribute instead of id. I changed and it's creating single resource tag in the resources.xml file.
thanks for helping me to resolve this issue.

**Comment by purush123** [comment]
We bound the DB service as CUPS. Also, in WEB-INF/resources.xml, we have placed the resources.xml with values for maxActive, etc
The merged resources.xml generated by TomEE inside PCF is shown below (obtained through SSH):
<resources>
    <Resource id='jdbc/JNDIName' type='javax.sql.DataSource' removeAbandonedTimeout='300' logAbandoned='true' removeAbandoned='true' initialSize='50' maxActive='50' minIdle='0' maxIdle='50' properties-provider='org.cloudfoundry.reconfiguration.tomee.DelegatingPropertiesProvider'/>    
</resources>

But, the maxActive, minIdle parameter is not picked by the application running in PCF using TomEE buildpack.
For maxActive='50' shown above, we have not given value of 50 with single quotes in WEB-INF/resources.xml. TomEE adds single quotes.

**Comment by violetagg** [comment]
@purush123 Hi, if you think there is an issue please open a new one. This one is solved.
