### ISSUE TITLE
Using Oracle Service provided by CUPS does not load the driver properly

### ISSUE THREAD

**Issue by mgvinuesa** [cloudfoundry-community/tomee-buildpack#31]
Hi,

I have defined a CUPS for accessing to a oracle database and the driver is not loaded/detected when the application (EAR with different WARs) starts.

To define my cups I have tried few combinations by anyone works properly

1. Defining with all the params: cf cups ARQRUNDataSource -p "hostname,port,name, username,password"

It generates the following VCAP_SERVICES

```
 "VCAP_SERVICES": {
  "user-provided": [
   {
    "credentials": {
     "hostname": "<domain>",
     "name": "<servicename>",
     "password": "<password>",
     "port": "<port>",
     "username": "<username>"
    },
    "label": "user-provided",
    "name": "ARQRUNDataSource",
    "syslog_drain_url": "",
    "tags": []
   }
  ]
 }
}
```

2. Using URI param: cf cups ARQRUNDataSource -p {"uri"}

Where the URI has the following value: 
`oracle://<username>:<password>@<host>:<port>/<serviceName>`

It generates the following VCAP_SERVICES

```
"VCAP_SERVICES": {
 "user-provided": [
  {
   "credentials": {
    "uri": "oracle://<username>:<password>@<hostname>:<port>/<servicename>"
   },
   "label": "user-provided",
   "name": "ARQRUNDataSource",
   "syslog_drain_url": "",
   "tags": []
  }
 ]
}
```

I have followed for example the following references:

[Deliver Service Credentials to an Application](https://docs.cloudfoundry.org/devguide/services/user-provided.html)
[Binding Credentials](http://docs.pivotal.io/pivotalcf/2-0/services/binding-credentials.html)

When the application starts I can see the following logs about HSQLDB:

```
  2018-02-22T16:26:37.82+0100 [App/0] OUT [CONTAINER] OpenEJB.startup.config                             INFO    Configuring Service(id=Default JDBC Database, type=Resource, provider-id=De
atabase)
  2018-02-22T16:26:37.82+0100 [App/0] OUT [CONTAINER] OpenEJB.startup.config                             INFO    Auto-creating a Resource with id 'Default JDBC Database' of type 'javax.sql
for 'WebApp_ID.Comp1361995231'.
  2018-02-22T16:26:37.83+0100 [App/0] OUT [CONTAINER] OpenEJB.startup.service                            INFO    Creating Resource(id=Default JDBC Database)
  2018-02-22T16:26:38.17+0100 [App/0] OUT [CONTAINER] hsqldb.db.HSQLDB61BE1F9C4E.ENGINE                  INFO    Checkpoint start
  2018-02-22T16:26:38.17+0100 [App/0] OUT [CONTAINER] hsqldb.db.HSQLDB61BE1F9C4E.ENGINE                  INFO    checkpointClose start
  2018-02-22T16:26:38.19+0100 [App/0] OUT [CONTAINER] hsqldb.db.HSQLDB61BE1F9C4E.ENGINE                  INFO    checkpointClose end
  2018-02-22T16:26:38.19+0100 [App/0] OUT [CONTAINER] hsqldb.db.HSQLDB61BE1F9C4E.ENGINE                  INFO    Checkpoint end - txts: 1
  2018-02-22T16:26:38.21+0100 [App/0] OUT [CONTAINER] OpenEJB.startup.config                             INFO    Auto-linking resource-ref 'jdbc/ARQRUNDataSource' in bean WebApp_ID.Comp136
esource(id=Default JDBC Database)
```
As you can see it links with HSQLDB instead use my oracle driver, I don't know why. How can "force" the driver class name by cups?

My EAR is like these logs

```
EAR
   |__drivers
   |_____ojdbc6.jar
   |__META-INF
   |_____application.xml
   |__application1.war
```

**Comment by violetagg** [comment]
Hi,

For CUPS we are searching for `creds['jdbcUrl'].start_with?('jdbc:mysql', 'jdbc:postgresql', 'jdbc:oracle', 'jdbc:db2', 'jdbc:sqlserver')`
https://github.com/cloudfoundry-community/tomee-buildpack/blob/master/lib/java_buildpack/container/tomee/tomee_resource_configuration.rb#L83

so if the url starts with `jdbc:oracle` it should be working.

Regards,
Violeta

**Comment by mgvinuesa** [comment]
Ok, it loads the drivers but it does not connect properly.

`cf create-user-provided-service ARQRUNDataSource -p "{"jdbcUrl":"jdbc:oracle:thin:<username>/<password>@<host>:<port>/<serviceName>"}"`

That generates me the following VCAP

```
{
 "VCAP_SERVICES": {
  "user-provided": [
   {
    "credentials": {
     "jdbcUrl": "jdbc:oracle:thin:<username>/<password>@<host>:<port>/<serviceName>"
    },
    "label": "user-provided",
    "name": "ARQRUNDataSource",
    "syslog_drain_url": "",
    "tags": []
   }
  ]
 }
}
```

But i get an error from the database

 ```
2018-02-22T18:32:45.61+0100 [App/0] OUT Caused by: java.sql.SQLException: ORA-01017: invalid username/password; logon denied
 2018-02-22T18:32:45.61+0100 [App/0] OUT      at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
 2018-02-22T18:32:45.61+0100 [App/0] OUT      at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:389)
 2018-02-22T18:32:45.61+0100 [App/0] OUT      at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:382)
 2018-02-22T18:32:45.61+0100 [App/0] OUT      at oracle.jdbc.driver.T4CTTIfun.processError(T4CTTIfun.java:675)
 2018-02-22T18:32:45.61+0100 [App/0] OUT      at oracle.jdbc.driver.T4CTTIoauthenticate.processError(T4CTTIoauthenticate.java:448)
 2018-02-22T18:32:45.61+0100 [App/0] OUT      at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
 2018-02-22T18:32:45.61+0100 [App/0] OUT      at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
 2018-02-22T18:32:45.61+0100 [App/0] OUT      at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:383)
 2018-02-22T18:32:45.61+0100 [App/0] OUT      at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:776)
 2018-02-22T18:32:45.61+0100 [App/0] OUT      at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:432)
 2018-02-22T18:32:45.61+0100 [App/0] OUT      at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:553)
 2018-02-22T18:32:45.61+0100 [App/0] OUT      at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:254)
 2018-02-22T18:32:45.61+0100 [App/0] OUT      at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)
 2018-02-22T18:32:45.61+0100 [App/0] OUT      at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:528)
```
This jdbcUrl i'm just using in java simple java main and the connection works properly


                ```
                String jdbcUrl = "jdbc:oracle:thin:<username>/<password>@<host>:<port>/<serviceName>";
                Connection conn = null;
		Statement stmt = null;
		ResultSet rs = null;

		try {
			conn = DriverManager.getConnection(jdbcUrl);
			stmt = conn.createStatement();
			rs = stmt.executeQuery("SELECT SEQ_CONTRATOS.nextval as ID FROM DUAL");

			// Step 4 - Get result
			if (rs.next()) {
				System.out.println(rs.getString(1));
			}

		} catch (SQLException e) {

```
¿should be this binding transparent or maybe the jdbcUrl is modified or parsed?

Regards.
Manuel

**Comment by violetagg** [comment]
Can you try with this
`cf create-user-provided-service ARQRUNDataSource -p "{"jdbcUrl":"jdbc:oracle:thin:@<host>:<port>/<serviceName>","UserName":"<username>","Password":"<password>"}"`

**Comment by violetagg** [comment]
Hey,

Can you try with TomEE installed on a local machine?
Setup the datasource in the resource.xml and tell us whether the application is working.

Thanks,
Violeta

**Comment by mgvinuesa** [comment]
Hey 

It works perfect.

tomee.xml resource declaration:

```
  <Resource id="ARQRUNDataSource" type="javax.sql.DataSource">
    #  Oracle example
    #
    #  This connector will not work until you download the driver at:
    #  http://otn.oracle.com/software/tech/java/sqlj_jdbc/content.html
    JdbcDriver  oracle.jdbc.OracleDriver
    JdbcUrl jdbc:oracle:thin:@<host>:<port>/<serviceName>
    UserName    <username>
    Password    <password>
</Resource>
```
Log:

```
26-Feb-2018 17:11:26.516 INFORMACIÓN [main] org.apache.openejb.config.ConfigurationFactory.configureService Configuring Service(id=ARQRUNDataSource, type=Resource, provider-id=Default JDBC Database)
26-Feb-2018 17:11:26.520 INFORMACIÓN [main] org.apache.openejb.util.OptionsLog.info Using 'openejb.deployments.classpath=false'
26-Feb-2018 17:11:26.524 INFORMACIÓN [main] org.apache.openejb.assembler.classic.Assembler.createRecipe Creating TransactionManager(id=Default Transaction Manager)
26-Feb-2018 17:11:26.627 INFORMACIÓN [main] org.apache.openejb.assembler.classic.Assembler.createRecipe Creating SecurityService(id=Tomcat Security Service)
26-Feb-2018 17:11:26.665 INFORMACIÓN [main] org.apache.openejb.assembler.classic.Assembler.createRecipe Creating Resource(id=ARQRUNDataSource)
```

And result is Ok. I have also made the test informing only the jdbcUrl with username/password in the declaration:

```
  <Resource id="ARQRUNDataSource" type="javax.sql.DataSource">
    #  Oracle example
    #
    #  This connector will not work until you download the driver at:
    #  http://otn.oracle.com/software/tech/java/sqlj_jdbc/content.html
    JdbcDriver  oracle.jdbc.OracleDriver
    JdbcUrl jdbc:oracle:thin:<username>/<password>@<host>:<port>/<serviceName>
</Resource
```>

And I get the same error so I think that maybe this code in the provider:

`org.cloudfoundry.reconfiguration.tomee.provider.RelationalServicePropertiesProvider`

![image](https://user-images.githubusercontent.com/11572462/36681435-ee66863e-1b18-11e8-8179-db9bf1dcd1ce.png)

It is not parsing (I think) correctly the username and password, I'm going to debug in local your buildpack to try to detect if it is correct.

**Comment by mgvinuesa** [comment]
Ok I got it, as I put above it is a problem parsing the username and the password.

If you check the following class:

`org.cloudfoundry.reconfiguration.tomee.org.springframework.cloud.cloudfoundry.RelationalServiceInfoCreator` (or the spring cloud class)

The serviceinfo is created with the VCAPs credentials

![image](https://user-images.githubusercontent.com/11572462/36688149-d981a790-1b2b-11e8-9c31-7eb0fe3c6c72.png)

Here you can have the following scenarios:

1) If you only provide jdbcUrl, the URI is the jdbcUrl
The jdbcUrl is parsed as an URI and the username and password is not recovered due to a jdbcUrl as the following is not a proper URI:

`jdbc:oracle:thin:<username>/<password>@<host>:<port>/<serviceName>`

![image](https://user-images.githubusercontent.com/11572462/36689347-6c6ba15c-1b2f-11e8-9f28-f7e021d1d871.png)

2) if you don't provide jdbcUrl the tomEE does not load the driver

So for CUPS with tomEE you need to inform both variables. I don't believed that it is possible to make an implementation in the tomEE buildpack to solve this case but at least maybe would be interesting to document.

Regards.

Close the issue.

**Comment by mgvinuesa** [comment]
I have renamed the issue to inform it correctly.
