### ISSUE TITLE
Tomcat Logging support not working

### ISSUE THREAD

**Issue by cluebbe** [cloudfoundry-community/tomee-buildpack#40]
The following manifest.yml
`
---
applications:
- name: efa-service-app-efa-rest-prod
  path: build/efa-rest-1.0.2.war
  buildpacks:
  - https://github.com/cloudfoundry-community/tomee-buildpack.git
  env:
    JBP_CONFIG_TOMEE: '{ "tomee": {"version": "7.1.+"},"logging_support": {"repository_root": "https://java-buildpack.cloudfoundry.org/tomcat-logging-support","version": "2.5.0"}}'
`

leads to the following error during startup:
` 2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR Handler error
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR java.lang.ClassNotFoundException: com.gopivotal.cloudfoundry.tomcat.logging.CloudFoundryConsoleHandler
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:601)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:538)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at org.apache.juli.ClassLoaderLogManager.readConfiguration(ClassLoaderLogManager.java:336)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at java.util.logging.LogManager$3.run(LogManager.java:399)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at java.util.logging.LogManager$3.run(LogManager.java:396)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at java.security.AccessController.doPrivileged(Native Method)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:396)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at java.util.logging.LogManager.access$800(LogManager.java:145)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at java.util.logging.LogManager$2.run(LogManager.java:345)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at java.security.AccessController.doPrivileged(Native Method)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at java.util.logging.LogManager.getLogManager(LogManager.java:378)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at java.util.logging.Logger.demandLogger(Logger.java:448)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at java.util.logging.Logger.getLogger(Logger.java:502)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at org.apache.tomee.jul.formatter.log.JULLogger.<init>(JULLogger.java:67)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at org.apache.tomee.jul.formatter.log.ReloadableLog$ReloadableLogHandler.initDelegate(ReloadableLog.java:93)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at org.apache.tomee.jul.formatter.log.ReloadableLog$ReloadableLogHandler.<init>(ReloadableLog.java:54)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at org.apache.tomee.jul.formatter.log.ReloadableLog.newLog(ReloadableLog.java:37)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at org.apache.tomee.jul.formatter.log.TomEELog.<init>(TomEELog.java:79)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:121)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:141)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at org.apache.juli.logging.LogFactory.getLog(LogFactory.java:196)
   2021-03-03T16:35:13.45+0100 [APP/PROC/WEB/0] ERR 	at org.apache.catalina.startup.Bootstrap.<clinit>(Bootstrap.java:52)`

This happens even though the log states that it downloaded the respective JAR-File:
` 2021-03-03T17:06:35.01+0100 [STG/0] OUT [1m[31m----->[0m[22m Downloading [1m[34mTomcat Logging Support[0m[22m [34m2.5.0_RELEASE[0m from https://java-buildpack.cloudfoundry.org/tomcat-logging-support/tomcat-logging-support-2.5.0_RELEASE.jar [3m[32m(0.0s)[0m[23m`

Looking into the tomcat/libs folder on the server, the tomcat-logging-support-2.5.0_RELEASE.jar is missing. I guess this should be included there by the buildpack? Any ideas how I get the logging working?

**Comment by cluebbe** [comment]
Applied the changes of this Pull-Request and now works like a charm: [https://github.com/cloudfoundry-community/tomee-buildpack/pull/36](https://github.com/cloudfoundry-community/tomee-buildpack/pull/36)
