### ISSUE TITLE
Getting an error when building offline tomee buildpack 

### ISSUE THREAD

**Issue by phong2tran** [cloudfoundry-community/tomee-buildpack#43]
I'm trying to build the latest tomee offline buildpack (https://github.com/cloudfoundry-community/tomee-buildpack/archive/refs/tags/v4.34.zip) and got the following error:

deployment-vm/6bbd056e-73e7-40ea-adb1-acd7fd16e39d:~/workspace/buildpacks/tomee-buildpack-4.34$ bundle exec rake clean package OFFLINE=true PINNED=true
Pinning groovy version to 2.5.9
Pinning spring_boot_cli version to 2.3.5_RELEASE
Pinning tomee version to 7.0.5
Pinning lifecycle_support version to 2.5.0_RELEASE
Pinning logging_support version to 2.5.0_RELEASE
Pinning access_logging_support version to 2.5.0_RELEASE
Pinning resource_configuration version to 1.5.0_RELEASE
Pinning redis_store version to 1.3.6_RELEASE
Pinning jre version to 11.0.12_7
Pinning jre version to 14.0.2_13
Pinning jre version to 1.8.0_275
Pinning jvmkill_agent version to 1.16.0_RELEASE
Pinning memory_calculator version to 3.13.0_RELEASE
Pinning app_dynamics_agent version to 20.10.0_31173
[VersionResolver]                WARN  Discarding illegal version 2.4.0-BETA: Invalid micro version '0-BETA'
Pinning azure_application_insights_agent version to 2.6.2
Pinning client_certificate_mapper version to 1.11.0_RELEASE
Pinning container_customizer version to 2.6.0_RELEASE
Pinning container_security_provider version to 1.18.0_RELEASE
Pinning contrast_security_agent version to 3.7.10_17525
Pinning dynatrace_appmon_agent version to 7.1.0_1803
Pinning elastic_apm_agent version to 1.18.1
Pinning google_stackdriver_debugger version to 2.26.0
Pinning google_stackdriver_profiler version to 0.1.0
[DownloadCache]                  WARN  Request failure 1, retrying after 5s.  Failure: 403 Forbidden
Forbidden!
[DownloadCache]                  WARN  Request failure 2, retrying after 10s.  Failure: 403 Forbidden
Forbidden!
[DownloadCache]                  WARN  Request failure 3, retrying after 20s.  Failure: 403 Forbidden
Forbidden!
[DownloadCache]                  WARN  Request failure 4, retrying after 40s.  Failure: 403 Forbidden
Forbidden!
[DownloadCache]                  WARN  Request failure 5, retrying after 60s.  Failure: 403 Forbidden
Forbidden!
[InternetAvailability]           WARN  Internet availability set to false: Request failed: 403 Forbidden
Forbidden!
**[DownloadCache]                  WARN  Unable to download https://ca.bintray.com/apm-agents/index.yml into cache build/staging/resources/cache: 403 Forbidden**
Forbidden!
rake aborted!
Unable to find cached file for https://ca.bintray.com/apm-agents/index.yml
/var/vcap/store/deployment-vm/home/ptran/workspace/buildpacks/tomee-buildpack-4.34/lib/java_buildpack/util/cache/download_cache.rb:79:in `get'
/var/vcap/store/deployment-vm/home/ptran/workspace/buildpacks/tomee-buildpack-4.34/rakelib/dependency_cache_task.rb:183:in `get_from_cache'
/var/vcap/store/deployment-vm/home/ptran/workspace/buildpacks/tomee-buildpack-4.34/rakelib/dependency_cache_task.rb:175:in `block (2 levels) in uris'
/var/vcap/store/deployment-vm/home/ptran/workspace/buildpacks/tomee-buildpack-4.34/rakelib/dependency_cache_task.rb:173:in `each'
/var/vcap/store/deployment-vm/home/ptran/workspace/buildpacks/tomee-buildpack-4.34/rakelib/dependency_cache_task.rb:173:in `block in uris'
/var/vcap/store/deployment-vm/home/ptran/workspace/buildpacks/tomee-buildpack-4.34/rakelib/dependency_cache_task.rb:172:in `each'
/var/vcap/store/deployment-vm/home/ptran/workspace/buildpacks/tomee-buildpack-4.34/rakelib/dependency_cache_task.rb:172:in `uris'
/var/vcap/store/deployment-vm/home/ptran/workspace/buildpacks/tomee-buildpack-4.34/rakelib/dependency_cache_task.rb:46:in `initialize'
/var/vcap/store/deployment-vm/home/ptran/workspace/buildpacks/tomee-buildpack-4.34/Rakefile:42:in `new'
/var/vcap/store/deployment-vm/home/ptran/workspace/buildpacks/tomee-buildpack-4.34/Rakefile:42:in `<top (required)>'
/home/ptran/.rbenv/versions/2.5.8/bin/bundle:23:in `load'
/home/ptran/.rbenv/versions/2.5.8/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)

It looked like the build process (package task) was trying to download a package index (https://ca.bintray.com/apm-agents/index.yml?) and got 403 forbidden error.

Any idea what could be wrong and how can we fix this issue?

**Comment by phong2tran** [comment]
I tried to access the same index.yml (https://ca.bintray.com/apm-agents/index.yml) in Chrome and got the same forbidden error. See the attached screenshot.

![chrome_2021-08-02_00-38-36](https://user-images.githubusercontent.com/29740500/127822394-7978bb27-bcb6-428e-b20c-b0ebea020df0.png)

**Comment by dmikusa** [comment]
[Bintray was shutdown](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) so that's likely why your link isn't working anymore. 

You need to [update this config](https://github.com/cloudfoundry-community/tomee-buildpack/blob/main/config/introscope_agent.yml#L19) to point to the same place as [this config](https://github.com/cloudfoundry/java-buildpack/blob/main/config/introscope_agent.yml#L19). That should get you working.
